### ISSUE TITLE
Browser Implication: webRTC not recognized by Node

### ISSUE THREAD

**Issue by F1nx** [F1nx/swerve#3]
In testing the first push for the pre-release, I realize that there should be some kind of browser implementation with `swerve` because it is not recognized by NodeJS. How we go about that is open for discussion. I'm thinking Electron  or a somewhat vanilla solution with simple HTML code so it can still be used and customized by other people (as opposed to a framework).

**Comment by fr33roam3r** [comment]
To narrow down our options, at least we know that the solution must be able to run Node (duh)!

**Comment by F1nx** [comment]
Are there any demonstrations of webRTC outside of the browser?

**Comment by F1nx** [comment]
Maybe the UI should be as another repo since we want to use this one as a template (though we will likely have to do the testing there, too).

**Comment by F1nx** [comment]
We can always bundle the scripts together for deployment!
